using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using gearOps.Infrastructure.Data;

#nullable disable

namespace gearOps.Infrastructure.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513143000_PurchaseOrderWorkflow")]
    public partial class PurchaseOrderWorkflow : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE purchase_orders
                    ALTER COLUMN invoice_number DROP NOT NULL;

                ALTER TABLE purchase_orders
                    ADD COLUMN IF NOT EXISTS confirmed_at timestamp with time zone,
                    ADD COLUMN IF NOT EXISTS delivered_at timestamp with time zone,
                    ADD COLUMN IF NOT EXISTS sent_to_vendor_at timestamp with time zone,
                    ADD COLUMN IF NOT EXISTS status integer NOT NULL DEFAULT 0;

                UPDATE purchase_orders
                SET status = 3,
                    delivered_at = COALESCE(delivered_at, order_date)
                WHERE delivered_at IS NULL
                    AND status = 0;

                CREATE TABLE IF NOT EXISTS purchase_order_logs (
                    purchase_order_log_id integer GENERATED BY DEFAULT AS IDENTITY,
                    purchase_order_id integer NOT NULL,
                    from_status integer NULL,
                    to_status integer NULL,
                    action text NOT NULL,
                    notes text NULL,
                    email_sent_to_vendor boolean NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT pk_purchase_order_logs PRIMARY KEY (purchase_order_log_id),
                    CONSTRAINT fk_purchase_order_logs_purchase_orders_purchase_order_id
                        FOREIGN KEY (purchase_order_id)
                        REFERENCES purchase_orders (purchase_order_id)
                        ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ix_purchase_order_logs_purchase_order_id
                    ON purchase_order_logs (purchase_order_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "purchase_order_logs");

            migrationBuilder.DropColumn(
                name: "confirmed_at",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "delivered_at",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "sent_to_vendor_at",
                table: "purchase_orders");

            migrationBuilder.DropColumn(
                name: "status",
                table: "purchase_orders");

            migrationBuilder.AlterColumn<string>(
                name: "invoice_number",
                table: "purchase_orders",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);
        }
    }
}
