// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gearOps.Infrastructure.Data;

#nullable disable

namespace gearOps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gearOps.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("AppointmentId")
                        .HasName("pk_appointments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_appointments_customer_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_appointments_vehicle_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.LowStockAlert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alert_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("AlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alerted_at");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<int>("StockAtAlert")
                        .HasColumnType("integer")
                        .HasColumnName("stock_at_alert");

                    b.HasKey("AlertId")
                        .HasName("pk_low_stock_alerts");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_low_stock_alerts_part_id");

                    b.ToTable("low_stock_alerts", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.LoyaltyDiscount", b =>
                {
                    b.Property<int>("LoyaltyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("loyalty_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoyaltyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_applied");

                    b.Property<decimal>("PurchaseAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("purchase_amount");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_invoice_id");

                    b.HasKey("LoyaltyId")
                        .HasName("pk_loyalty_discounts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_loyalty_discounts_customer_id");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_loyalty_discounts_sales_invoice_id");

                    b.ToTable("loyalty_discounts", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("log_type");

                    b.Property<int>("MailedStatus")
                        .HasColumnType("integer")
                        .HasColumnName("mailed_status");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal>("CostPricePerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_price_per_unit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_name");

                    b.Property<decimal>("SellingPricePerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("selling_price_per_unit");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.HasKey("PartId")
                        .HasName("pk_parts");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_parts_vendor_id");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.PartRequest", b =>
                {
                    b.Property<int>("PartRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("part_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartRequestId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_name");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("PartRequestId")
                        .HasName("pk_part_requests");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_part_requests_customer_id");

                    b.ToTable("part_requests", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("purchase_order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.HasKey("PurchaseOrderId")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_purchase_orders_vendor_id");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<int>("PurchaseOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("purchase_order_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseOrderItemId"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_unit");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("PurchaseOrderItemId")
                        .HasName("pk_purchase_order_items");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_purchase_order_items_part_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_items_purchase_order_id");

                    b.ToTable("purchase_order_items", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_date");

                    b.HasKey("ReviewId")
                        .HasName("pk_reviews");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_reviews_appointment_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reviews_customer_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.SalesInvoice", b =>
                {
                    b.Property<int>("SalesInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sales_invoice_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalesInvoiceId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("final_amount");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paid");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("SalesInvoiceId")
                        .HasName("pk_sales_invoices");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_invoices_customer_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_sales_invoices_staff_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_sales_invoices_vehicle_id");

                    b.ToTable("sales_invoices", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.SalesInvoiceItem", b =>
                {
                    b.Property<int>("SalesInvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sales_invoice_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalesInvoiceItemId"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_unit");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_invoice_id");

                    b.HasKey("SalesInvoiceItemId")
                        .HasName("pk_sales_invoice_items");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_sales_invoice_items_part_id");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_sales_invoice_items_sales_invoice_id");

                    b.ToTable("sales_invoice_items", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.ServiceRecord", b =>
                {
                    b.Property<int>("ServiceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceRecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<decimal>("ServiceCost")
                        .HasColumnType("numeric")
                        .HasColumnName("service_cost");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("service_date");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_description");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("ServiceRecordId")
                        .HasName("pk_service_records");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_service_records_appointment_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_service_records_staff_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_service_records_vehicle_id");

                    b.ToTable("service_records", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditsRemaining")
                        .HasColumnType("numeric")
                        .HasColumnName("credits_remaining");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_url");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("VehicleId")
                        .HasName("pk_vehicles");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_vehicles_customer_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendorId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor_name");

                    b.HasKey("VendorId")
                        .HasName("pk_vendors");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.User", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_users_customer_id");

                    b.HasOne("gearOps.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_vehicles_vehicle_id");

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.LowStockAlert", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.Part", "Part")
                        .WithMany("LowStockAlerts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_low_stock_alerts_parts_part_id");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.LoyaltyDiscount", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.User", "Customer")
                        .WithMany("LoyaltyDiscounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loyalty_discounts_users_customer_id");

                    b.HasOne("gearOps.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("LoyaltyDiscounts")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loyalty_discounts_sales_invoices_sales_invoice_id");

                    b.Navigation("Customer");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Notification", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Part", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Parts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parts_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.PartRequest", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.User", "Customer")
                        .WithMany("PartRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_part_requests_users_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.Part", "Part")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_parts_part_id");

                    b.HasOne("gearOps.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_purchase_orders_purchase_order_id");

                    b.Navigation("Part");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Review", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Reviews")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_appointments_appointment_id");

                    b.HasOne("gearOps.Domain.Entities.User", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_customer_id");

                    b.Navigation("Appointment");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.SalesInvoice", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.User", "Customer")
                        .WithMany("CustomerInvoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoices_users_customer_id");

                    b.HasOne("gearOps.Domain.Entities.User", "Staff")
                        .WithMany("StaffInvoices")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoices_users_staff_id");

                    b.HasOne("gearOps.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoices_vehicles_vehicle_id");

                    b.Navigation("Customer");

                    b.Navigation("Staff");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.SalesInvoiceItem", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.Part", "Part")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_items_parts_part_id");

                    b.HasOne("gearOps.Domain.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_items_sales_invoices_sales_invoice_id");

                    b.Navigation("Part");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.ServiceRecord", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.Appointment", "Appointment")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_records_appointments_appointment_id");

                    b.HasOne("gearOps.Domain.Entities.User", "Staff")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_records_users_staff_id");

                    b.HasOne("gearOps.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_records_vehicles_vehicle_id");

                    b.Navigation("Appointment");

                    b.Navigation("Staff");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("gearOps.Domain.Entities.User", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("ServiceRecords");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Part", b =>
                {
                    b.Navigation("LowStockAlerts");

                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.SalesInvoice", b =>
                {
                    b.Navigation("LoyaltyDiscounts");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CustomerInvoices");

                    b.Navigation("LoyaltyDiscounts");

                    b.Navigation("Notifications");

                    b.Navigation("PartRequests");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("ServiceRecords");

                    b.Navigation("StaffInvoices");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("SalesInvoices");

                    b.Navigation("ServiceRecords");
                });

            modelBuilder.Entity("gearOps.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
